### ISSUE TITLE
MicrosoftTeams.GetChannelsForGroup failed: The method 'GetChannelsForGroup' has an invalid value for parameter 'groupId'

### ISSUE THREAD

**Issue by kenny-bui** [OfficeDev/microsoft-teams-apps-staffcheckins#4]
Get this error while creating check-in.
![image](https://user-images.githubusercontent.com/65940735/99641647-67372a80-29ff-11eb-9d55-eb8229d626ed.png)

Nothing shows when clicking the Team drop-down:
![image](https://user-images.githubusercontent.com/65940735/99642033-e2004580-29ff-11eb-98d6-1ea3550b15ea.png)

**Comment by v-smahaj** [comment]
We were not able to reproduce this issue at our end.
The dropdown shows all the groups owned by logged-in admin user. So, make sure that the admin who has logged-in belongs to few groups/teams.
