### ISSUE TITLE
Action 'Post_your_own_adaptive_card_as_the_Flow_bot_to_a_channel' failed

### ISSUE THREAD

**Issue by kenny-bui** [OfficeDev/microsoft-teams-apps-staffcheckins#5]
Flow: Staff Check-ins Adhoc Schedules
Team connection uses a service account which not member of any teams. (Do I need to add the service account to teams to make it work or the flow should run based on the context of the current user who created the check-ins?)
![image](https://user-images.githubusercontent.com/65940735/99655674-da956800-2a10-11eb-8363-8a6d46f12986.png)

**Comment by abbodh** [comment]
Hi @kenny-bui , yes you will have to add the service account as team member. Flow while sending the notification checks internally (I guess) whether you are a valid team member or not. 

Can you try it once.
