### ISSUE TITLE
Showing error in Staff check-in Admin app

### ISSUE THREAD

**Issue by umeshkumarchauhan** [OfficeDev/microsoft-teams-apps-staffcheckins#7]
Facing the below error in Staff check-in Admin app

Error 1 : Office365Users.UserPhotoMetadata failed: { "error": { "code": "AuthenticationError", "message": "Error authenticating with resource", "innerError": { "date": "2021-01-02T12:32:10", "request-id": "64eba922-7014-4287-a625-b9a45620f264", "client-request-id": "64eba922-7014-4287-a625-b9a45620f264" } } }

Error 2: Office365Groups.ListGroupMembers failed: The method 'ListGroupMembers' has an invalid value for parameter 'groupId'

Error 3 : Office365Users.UserPhotoMetadata failed: The method 'UserPhotoMetadata' has an invalid value for parameter 'userId'

**Comment by v-shakin** [comment]
Hi @umeshkumarchauhan 
Can you please try the below approaches as mentioned - 

Error 1:
This error appears if logged in user doesn't have UserPhoto.
We have handled it to show a sample image but if you still get the issue, please follow below steps:
1) navigate to [make.powerapps.com](make.powerapps.com)
2) Click on Apps in left Navigation bar
3) click on '...' , Select Edit
4) Once the app is opened, In the left side, Search for Image4 .
5) Click on Image4, Change its image property to
If(
Office365Users.UserPhotoMetadata(ThisItem.UserTitle).HasPhoto = true,
Office365Users.UserPhoto(ThisItem.UserEmail),
'dummy_user@1x'
)
6)Save and publish the app

Error 2:
This error occurs if the group id parameter is not valid/empty.
1)Can you please check if any team which has a check-in request is deleted.
There would be possibility that, a check-in for a team is created and the respective team is deleted.

If the team for which the check-in request was submitted still exists then please provide more details about the issue (screenshot of the screen where you are getting error).

Error 3:
Resolving error 1 would fix this issue.

**Comment by umeshkumarchauhan** [comment]
Hello Aryank ,

Please find below response.

Regards,
Umesh Chauhan

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
