### ISSUE TITLE
Staff Check-In Admin App Error

### ISSUE THREAD

**Issue by h3rdy4n** [OfficeDev/microsoft-teams-apps-staffcheckins#8]
Hi, 

I'm facing an error when I'm trying to open the Staff Check-In Admin app in Teams. 

StaffCheckinReports.Run failed: { "error": { "code": 502, "source": "asia-001.azure-apim.net", "clientRequestId": "070e9260-4b2f-4172-a3be-93aeba5303a4", "message": "BadGateway", "innerError": { "error": { "code": "NoResponse", "message": "The server did not receive a response from an upstream server. Request tracking id '08585848608506287191547506111CU05'." } } } }

Can you advise? 

Thanks,
Herdyan

**Comment by v-smahaj** [comment]
We are not able to reproduce this issue at our end.
Make sure in 'StaffCheckinReports flow', in 'Get items' step you have entered correct SharePoint site address and list name is updated. If that doesn’t help, then Navigate to the Power App and select scrnCheckInReport.
With scrnCheckInReport selected, choose OnVisible in the dropdown in the upper left corner. In the formula bar, copy the formula to notepad, remove the formula, then replace it all over again, then save and publish the app and try to run.
Let us know if issue still persists.
